# **CLASE 4 (Primera parte)**

Librerías:
- Numpy
- Pandas

## **Numpy:**




Proporciona las estructuras de datos básicas implementando matrices y arreglos multidimensionales. También proporciona las funcionalidades necesarias para crear y manipular estas estructuras de datos.

In [ ]:
import numpy as np

In [ ]:
valores_celsius = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9,20.1]

In [ ]:
#Ejemplo utilizando Numpy
C = np.array(valores_celsius) #Se convierte la lista valores_celsius en un arrelgo de una dimensión en Numpy
print(C)
print(type(C))

F = (C*9/5+31)
print(F) #Se realiza la conversión a grados Farenheit usando una operación en el arreglo y se imprime
print(type(F))

[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]
<class 'numpy.ndarray'>
[67.18 68.44 70.42 71.5  71.86 71.14 70.24 69.16 68.62 67.18]
<class 'numpy.ndarray'>


In [ ]:
#Ejemplo utilizando listas en vez de Numpy
valores_farenheit = [x*9/5+31 for x in valores_celsius] #Se itera sobre la lista para ir calculando sobre cada valor
print(valores_farenheit)
print(type(valores_farenheit))

[67.18, 68.44, 70.42, 71.5, 71.86, 71.14, 70.24000000000001, 69.16, 68.62, 67.18]
<class 'list'>


## **Pandas:**

 Se utiliza para la manipulación y el análisis de datos. Asimismo, proporciona estructuras de datos y operaciones especiales para la manipulación de tablas numéricas y series temporales.

Las estructuras de datos más importantes de esta librería son *Series* y *DataFrame*

***Series***

- Es un objeto unidimensional
- Puede contener cualquier tipo de dato
- Contiene dos arreglos: uno que funciona como índice y el otro que contiene los datos

In [ ]:
import pandas as pd

In [ ]:
obj = pd.Series([4,7,-5,3])
obj

#El índice es la columna de lado izquierdo y los datos el del lado derecho

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
#Para reemplazar un valor en nuestro arreglo
obj.replace(-5, 5, inplace=True) #X es el valor que queremos reemplazar, Y es el nuevo valor que queremos asignar (x,y)
                                 #Inplace modifica el arreglo directamente en vez de crear uno nuevo
obj

0    4
1    7
2    5
3    3
dtype: int64

In [ ]:
# Acceso al índice y a los valores de la serie

print(obj.index)
print(obj.values)

RangeIndex(start=0, stop=4, step=1)
[4 7 5 3]


In [ ]:
# Definición de objeto Serie con índices individuales

frutas = ['manzanas', 'naranjas', 'cerezas', 'peras'] #Creamos nuestro propio índice a través de una lista
cantidades = [20, 33, 52, 10] #Creamos nuestros propios datos a través de una lista
serie = pd.Series(cantidades, index=frutas) #Le indicamos cuál es nuestro índice y cuáles son los datos
serie

manzanas    20
naranjas    33
cerezas     52
peras       10
dtype: int64

In [ ]:
#Si se suman dos series con el mismo índice, se obtiene una nueva serie con el mismo índice y los valores correspondientes se suman

serie = pd.Series(cantidades, index=frutas)
serie2 = pd.Series([17, 13, 31, 32], index=frutas) #le damos los datos que queremos que tenga la serie 2
print(serie + serie2) #sumamos ambas series

print("La suma de la primera serie es: ", sum(serie))
print("La suma de la segunda serie es: ", sum(serie2))

manzanas    37
naranjas    46
cerezas     83
peras       42
dtype: int64
La suma de la primera serie es:  115
La suma de la segunda serie es:  93


***DataFrame***

- Contiene una colección ordenada de columnas con nombre, cada una de las cuales puede tener un tipo d valor diferente.
- Tiene un índice de fila y uno de columna

In [ ]:
#Creación de un diccionario de datos

datos = {"estado":["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada", "Nebraska","Nebraska","Nebraska", "Texas","Texas","Texas"],
         "año":["2000", "2001", "2002", "2001", "2002", "2003","2000","2002","2004","2001","2002","2003"],
         "población (millones)":[1.5, 1.7, 3.6, 2.4, 2.9, 3.2, 1.3, 2.6, 4.3, 2.3, 4.5, 6.7]}

print(type(datos))

<class 'dict'>


In [ ]:
#Para convertir un diccionario en un DataFrame

frame = pd.DataFrame(datos)
frame

estado   año  población (millones)
0       Ohio  2000                   1.5
1       Ohio  2001                   1.7
2       Ohio  2002                   3.6
3     Nevada  2001                   2.4
4     Nevada  2002                   2.9
5     Nevada  2003                   3.2
6   Nebraska  2000                   1.3
7   Nebraska  2002                   2.6
8   Nebraska  2004                   4.3
9      Texas  2001                   2.3
10     Texas  2002                   4.5
11     Texas  2003                   6.7

In [ ]:
#La función head selecciona solo las primeras cinco filas

frame.head()

estado   año  población (millones)
0    Ohio  2000                   1.5
1    Ohio  2001                   1.7
2    Ohio  2002                   3.6
3  Nevada  2001                   2.4
4  Nevada  2002                   2.9

In [ ]:
#La función tail selecciona las últimas cinco

frame.tail()

estado   año  población (millones)
7   Nebraska  2002                   2.6
8   Nebraska  2004                   4.3
9      Texas  2001                   2.3
10     Texas  2002                   4.5
11     Texas  2003                   6.7

In [ ]:
#Se pueden especificar el orden en como aparezcan las columnas en nuestro DataFrame

pd.DataFrame(datos, columns=["año", "estado", "población (millones)"])

año    estado  población (millones)
0   2000      Ohio                   1.5
1   2001      Ohio                   1.7
2   2002      Ohio                   3.6
3   2001    Nevada                   2.4
4   2002    Nevada                   2.9
5   2003    Nevada                   3.2
6   2000  Nebraska                   1.3
7   2002  Nebraska                   2.6
8   2004  Nebraska                   4.3
9   2001     Texas                   2.3
10  2002     Texas                   4.5
11  2003     Texas                   6.7

In [ ]:
#Para renombrar las columnas utilizando la función rename

frame.rename(columns={"estado": "Estado",
                      "año": "Año",
                      "población (millones)": "Población (Millones)"},
             inplace=True) #Inplace modifica el dataframe directamente en vez de crear uno nuevo
frame

Estado   Año  Población (Millones)
0       Ohio  2000                   1.5
1       Ohio  2001                   1.7
2       Ohio  2002                   3.6
3     Nevada  2001                   2.4
4     Nevada  2002                   2.9
5     Nevada  2003                   3.2
6   Nebraska  2000                   1.3
7   Nebraska  2002                   2.6
8   Nebraska  2004                   4.3
9      Texas  2001                   2.3
10     Texas  2002                   4.5
11     Texas  2003                   6.7

In [ ]:
#Una columna en un DataFrame se puede recuperar como una serie

frame["Estado"] #Se pueden recuperar usando notación de lista: frame["nombre de la columna"]

0         Ohio
1         Ohio
2         Ohio
3       Nevada
4       Nevada
5       Nevada
6     Nebraska
7     Nebraska
8     Nebraska
9        Texas
10       Texas
11       Texas
Name: Estado, dtype: object

In [ ]:
frame.Año #O también usando la notación de punto: frame.nombredelacolumna

0     2000
1     2001
2     2002
3     2001
4     2002
5     2003
6     2000
7     2002
8     2004
9     2001
10    2002
11    2003
Name: Año, dtype: object

In [ ]:
#También se pueden ordenar según como se requiera

frame = frame.sort_values(by="Población (Millones)", ascending=False) #Ordenamos el DataFrame de mayor a menor según su población
frame

Estado   Año  Población (Millones)
11     Texas  2003                   6.7
10     Texas  2002                   4.5
8   Nebraska  2004                   4.3
2       Ohio  2002                   3.6
5     Nevada  2003                   3.2
4     Nevada  2002                   2.9
7   Nebraska  2002                   2.6
3     Nevada  2001                   2.4
9      Texas  2001                   2.3
1       Ohio  2001                   1.7
0       Ohio  2000                   1.5
6   Nebraska  2000                   1.3

In [ ]:
#Se pueden importar datos sin la necesidad de crearla nosotros

In [ ]:
pip install ucimlrepo #Se instala el repositorio de UCI

In [ ]:
from ucimlrepo import fetch_ucirepo #Instalamos una base de datos del repositiorio anterior

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)

{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org

In [ ]:
#Imprimimos lo que contiene el DataFrame x
X

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
#Imprimimos lo que contiene el DataFrame y
y

class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [ ]:
#Podemos tener una breve descripción estadística dentro del DataFrame

X.describe()

sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
y.describe()

class
count           150
unique            3
top     Iris-setosa
freq             50

In [ ]:
#También podemos obtener la cantidad de filas que corresponden a cada variable

y.value_counts() #En este caso solo lo hacemos con la variable y dado que esta contiene a nuestras categorías principales

class          
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
#Finalmente, podemos juntar bases de datos

pd.concat([y,X], axis="columns") #Le decimos que queremos concatenar el dataframe x con y a través del eje de las columnas

class  sepal length  sepal width  petal length  petal width
0       Iris-setosa           5.1          3.5           1.4          0.2
1       Iris-setosa           4.9          3.0           1.4          0.2
2       Iris-setosa           4.7          3.2           1.3          0.2
3       Iris-setosa           4.6          3.1           1.5          0.2
4       Iris-setosa           5.0          3.6           1.4          0.2
..              ...           ...          ...           ...          ...
145  Iris-virginica           6.7          3.0           5.2          2.3
146  Iris-virginica           6.3          2.5           5.0          1.9
147  Iris-virginica           6.5          3.0           5.2          2.0
148  Iris-virginica           6.2          3.4           5.4          2.3
149  Iris-virginica           5.9          3.0           5.1          1.8

[150 rows x 5 columns]